services:
  # Open WebUI
  open-webui:
    restart: unless-stopped
    build:
      context: ./webui
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    volumes:
      - ./open-webui-data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      # Set maximum log level
      GLOBAL_LOG_LEVEL: DEBUG
      # Open WebUI secret key
      WEBUI_SECRET_KEY: 123
      # Disable Open WebUI analytics
      SCARF_NO_ANALYTICS: true
      DO_NOT_TRACK: true
      ANONYMIZED_TELEMETRY: false
    extra_hosts:
      - host.docker.internal:host-gateway
