services:
  # Open WebUI
  open-webui:
    restart: unless-stopped
    build:
      context: ./webui
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    volumes:
      - ./open-webui-data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      OPENAI_API_BASE_URL: https://innoglobalhack-general.olymp.innopolis.university/v1
      OPENAI_API_KEY: "123"

      SCARF_NO_ANALYTICS: true
      DO_NOT_TRACK: true
      ANONYMIZED_TELEMETRY: false

      WEBUI_SECRET_KEY: "123"
    extra_hosts:
      - host.docker.internal:host-gateway

  # Apache Tika Server
  tika:
    restart: unless-stopped
    image: apache/tika:2.9.2.1-full
    command: -c /tika-config.xml
    ports:
      - "9998:9998"
    volumes:
      - ./tika-config.xml:/tika-config.xml
      - ./rus.traineddata:/tesseract-data/rus.traineddata
