services:
  # Open WebUI
  open-webui:
    restart: unless-stopped
    build:
      context: ./webui
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    volumes:
      - ./open-webui-data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      OPENAI_API_BASE_URL: https://innoglobalhack-general.olymp.innopolis.university/v1
      OPENAI_API_KEY: "123"

      SCARF_NO_ANALYTICS: true
      DO_NOT_TRACK: true
      ANONYMIZED_TELEMETRY: false

      WEBUI_SECRET_KEY: "123"
    extra_hosts:
      - host.docker.internal:host-gateway
